
Loading dataset...
Loaded data : 62235
batch_size = 128
learning rate = 0.0001
train_size = 49788
test_size = 12447
Data load complete!
Initializing model....
Initialize complete!!
Epoch 1
step : 4/389, train_loss : 740.7760620117188, test_loss : 763.3080444335938
CVAE_main.py:154: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "figsize" which is no longer supported as of 3.3 and will become an error in 3.6
  plt.savefig('recon.png', figsize=(16, 16))
CVAE_main.py:157: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "figsize" which is no longer supported as of 3.3 and will become an error in 3.6

























epoch 1 - average loss - train : 75.56200408935547, test : 76.16800689697266418
Epoch 2
























epoch 2 - average loss - train : 2.0460000038146973, test : 2.01700019836425877
Epoch 3
























epoch 3 - average loss - train : 0.5530000329017639, test : 0.554000020027160625
Epoch 4
























epoch 4 - average loss - train : 0.5480000376701355, test : 0.55000001192092957
Epoch 5

























epoch 5 - average loss - train : 0.5460000038146973, test : 0.548000037670135565
Epoch 6

























epoch 6 - average loss - train : 0.5460000038146973, test : 0.547000050544738864
Epoch 7


























epoch 7 - average loss - train : 0.5470000505447388, test : 0.548000037670135565
Epoch 8

























epoch 8 - average loss - train : 0.5470000505447388, test : 0.549000024795532275
Epoch 9


























epoch 9 - average loss - train : 0.5440000295639038, test : 0.545000016689300534
Epoch 10

























epoch 10 - average loss - train : 0.5460000038146973, test : 0.54800003767013557
Epoch 11

























epoch 11 - average loss - train : 0.5480000376701355, test : 0.54900002479553225
Epoch 12


























epoch 12 - average loss - train : 0.5520000457763672, test : 0.5540000200271606
Epoch 13






















step : 299/389, train_loss : 0.5600000023841858, test_loss : 0.5610000491142273
Traceback (most recent call last):
  File "CVAE_main.py", line 157, in <module>
    plt.savefig('x.png', figsize=(16, 16))
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 978, in savefig
    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 2060, in draw_idle
    self.draw(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 2845, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 646, in draw
    im, l, b, trans = self.make_image(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 956, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 492, in _make_image
    A_resampled = _resample(self, A_scaled, out_shape, t)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 193, in _resample
    _image.resample(data, out, transform,
KeyboardInterrupt
Traceback (most recent call last):
  File "CVAE_main.py", line 157, in <module>
    plt.savefig('x.png', figsize=(16, 16))
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 978, in savefig
    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 2060, in draw_idle
    self.draw(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 2845, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 646, in draw
    im, l, b, trans = self.make_image(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 956, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 492, in _make_image
    A_resampled = _resample(self, A_scaled, out_shape, t)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/image.py", line 193, in _resample
    _image.resample(data, out, transform,
KeyboardInterrupt